version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "5000:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

networks:
  backend:
    driver: bridge
  host:
    external: true

volumes:
  mongodb-data:
